superlists/urls.py
from django.conf.urls import url

from lists import views as list_views
from accounts import views as accounts_views

urlpatterns = [
    url(r"^$", list_views.home_page, name="home"),
    url(r"^lists/new$", list_views.new_list, name="new_list"),
    url(r"^lists/(\d+)/$", list_views.view_list, name="view_list"),
    url(r"^lists/(\d+)/add_item$", list_views.add_item, name="add_item"),
    url(
        r"^accounts/send_login_email$",
        accounts_views.send_login_email,
        name="send_login_email",
    ),
]

accounts/models.py
import uuid

from django.db import models


class User(models.Model):
    email = models.EmailField(primary_key=True)

    REQUIRED_FIELDS = []
    USERNAME_FIELD = "email"
    is_anonymous = False
    is_authenticated = True


class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4, max_length=40)

lists/models.py
from django.db import models


class List(models.Model):
    pass


class Item(models.Model):
    text = models.TextField(default="")
    list = models.ForeignKey(List, default=None)

accounts/views.py
from django.core.mail import send_mail
from django.shortcuts import redirect


def send_login_email(request):
    email = request.POST["email"]
    send_mail(
        "Your login link for Superlists",
        "body text tbc",
        "noreply@superlists",
        [email],
    )
    return redirect("/")

lists/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import redirect, render

from lists.models import Item, List


def home_page(request):
    return render(request, "home.html")


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    error = None

    if request.method == "POST":
        try:
            item = Item(text=request.POST["item_text"], list=list_)
            item.full_clean()
            item.save()
            return redirect(f"/lists/{list_.id}/")
        except ValidationError:
            error = "You can't have an empty list item"

    return render(request, "list.html", {"list": list_, "error": error})


def new_list(request):
    list_ = List.objects.create()
    item = Item(text=request.POST["item_text"], list=list_)
    try:
        item.full_clean()
        item.save()
    except ValidationError:
        list_.delete()
        error = "You can't have an empty list item"
        return render(request, "home.html", {"error": error})
    return redirect(f"/lists/{list_.id}/")


def add_item(request, list_id):
    list_ = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST["item_text"], list=list_)
    return redirect(f"/lists/{list_.id}/")

accounts/templates/login_email_sent.html
<html>
<h1>Email sent</h1>

<p>Check your email, you'll find a message with a link that will log you into
the site.</p>

</html>

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>To-Do lists</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <div class="container">

        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">Superlists</a>
                <form class="navbar-form navbar-right" method="POST" action="#">
                    <span>Enter email to log in:</span>
                    <input class="form-control" name="email" type="text" />
                    {% csrf_token %}
                </form>
            </div>
        </nav>

        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                {% block table %}
                {% endblock %}
            </div>
        </div>

    </div>
</body>

</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}/lists/new{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}/lists/{{ list.id }}/{% endblock %}

{% block table %}
<table id="id_list_table" class="table>
    {% for item in list.item_set.all %}
      <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
    {% endfor %}
  </table>
{% endblock %}